# Generated by Django 6.0 on 2026-01-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image_name_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
